// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmn_OqCAQsqneUwdmZ0yxk84JY9j3a_wo',
    appId: '1:373961493579:web:40147394747e55e85811ce',
    messagingSenderId: '373961493579',
    projectId: 'ccms-admin-app',
    authDomain: 'ccms-admin-app.firebaseapp.com',
    storageBucket: 'ccms-admin-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt9DgcO46MeSfzNEO3m4ny-N221iSONAw',
    appId: '1:373961493579:android:2b5b4d68529a3af85811ce',
    messagingSenderId: '373961493579',
    projectId: 'ccms-admin-app',
    storageBucket: 'ccms-admin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKpyMjxxtWD4R9S2hhvTWtYIR2a9zS2-w',
    appId: '1:373961493579:ios:9dd9a66fc6abb2c05811ce',
    messagingSenderId: '373961493579',
    projectId: 'ccms-admin-app',
    storageBucket: 'ccms-admin-app.firebasestorage.app',
    iosBundleId: 'com.example.ccmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKpyMjxxtWD4R9S2hhvTWtYIR2a9zS2-w',
    appId: '1:373961493579:ios:9dd9a66fc6abb2c05811ce',
    messagingSenderId: '373961493579',
    projectId: 'ccms-admin-app',
    storageBucket: 'ccms-admin-app.firebasestorage.app',
    iosBundleId: 'com.example.ccmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmn_OqCAQsqneUwdmZ0yxk84JY9j3a_wo',
    appId: '1:373961493579:web:982fcc7804b0181c5811ce',
    messagingSenderId: '373961493579',
    projectId: 'ccms-admin-app',
    authDomain: 'ccms-admin-app.firebaseapp.com',
    storageBucket: 'ccms-admin-app.firebasestorage.app',
  );
}
